name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        # Optionally you can configure which types are allowed.
        # Default: https://github.com/commitizen/conventional-commit-types
        with:
          types: fix, feat